tslearn-team/tslearn

setup.py

On machos you get the error
```bash
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c tslearn/cydtw.c -o build/temp.macosx-10.12-x86_64-3.6/tslearn/cydtw.o
tslearn/cydtw.c:517:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'clang' failed with exit status 1
----------------------------------------
Failed building wheel for tslearn
```
To fix this you need to add numpy include dirs flags in Extension calls.

Fix macosx build

---

setup.py

This PR makes sure that the LICENSE file is included in .tar.gz distributed on PyPi. Approach based on this [SO question](https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script), the alternative would be to write a `MANIFEST.in` file.
The corresponding issues was raised while packaging tslearn in conda-forge (see https://github.com/conda-forge/staged-recipes/pull/5275).
**Note:** I tested that this does include the `LICENSE` in the produced .tar.gz when running `python setup.py sdist`

Bundle the license file in distributed .tar.gz

---

tslearn/clustering.py
tslearn/cycc.pyx
tslearn/preprocessing.py

According to the issue #58 , here a proposal to improve clustering (only for the KShape method for now) by letting the user choose an initial guess as centroids. This guess is a numpy array of int which are the indices of the samples to be used as centroids instead of a random vector.

Add initial guess as centroid

---

tslearn/clustering.py
tslearn/docs/examples/plot_barycenter_interpolate.py
tslearn/docs/examples/plot_svm.py
tslearn/docs/gen_modules/backreferences/tslearn.barycenters.softdtw_barycenter.examples
tslearn/docs/gen_modules/backreferences/tslearn.datasets.CachedDatasets.examples
tslearn/docs/gen_modules/barycenters/tslearn.barycenters.dtw_barycenter_averaging.rst
tslearn/docs/gen_modules/barycenters/tslearn.barycenters.softdtw_barycenter.rst
tslearn/docs/gen_modules/metrics/tslearn.metrics.gamma_soft_dtw.rst
tslearn/docs/gen_modules/metrics/tslearn.metrics.sigma_gak.rst
tslearn/docs/gen_modules/svm/tslearn.svm.TimeSeriesSVC.rst
tslearn/docs/gen_modules/svm/tslearn.svm.TimeSeriesSVR.rst
tslearn/docs/variablelength.rst
tslearn/neighbors.py
tslearn/preprocessing.py
tslearn/svm.py
tslearn/tests/sklearn_patches.py
tslearn/tests/test_estimators.py
tslearn/tests/test_variablelength.py

This is an attempt to make it possible to use estimators with metrics like DTW on variable-length time series.
The first attempt here is to make DTW/soft-DTW usable for kNN estimators on variable-length time series.
The test I ran is:
```python
from tslearn.neighbors import KNeighborsTimeSeriesClassifier
from tslearn.utils import to_time_series_dataset
X = to_time_series_dataset([[1, 2, 3, 4], [1, 2, 3], [2, 5, 6, 7, 8, 9]])
y = [0, 0, 1]
clf = KNeighborsTimeSeriesClassifier(metric="dtw",
n_neighbors=1,
metric_params={"global_constraint": "sakoe_chiba"})
clf.fit(X, y)
print("---", clf._ts_fit)
print(clf.predict(X))
```
First, we have to think about whether the hack I introduced is a good way to reach our goal and second, once we have chosen a way to proceed, we will have to:
- do the same …

[WIP] Accept variable-length time series for some pairs metrics/estimators

---

tslearn/metrics.py

The values allowed for the parameter `global_constraint` were probably changed somewhere down the road, and the parameter value in `itakura_max_slope` was not updated accordingly.

Fix documentation for dtw_path

---

.travis.yml
setup.cfg
setup.py
tslearn/tests/sklearn_patches.py
tslearn/tests/test_estimators.py

Fixes #134 
As title says, the implicit imports are replaced with explicit imports in `test_estimators.py`.
It was a bit hard to find some of them from scikit-learn. Let's see if it improves code coverage.

Replace implicit imports with explicit imports

---

CHANGELOG.md
tslearn/__init__.py
tslearn/metrics.py
tslearn/tests/test_metrics.py

tslearn version: v0.2.0
Related to Issue: #140 
To be fixed:
1. itakura & sakoe-chiba are swapped in compute_mask (already fixed in initial commit)
2. for itakura: there should always be at least one path, whatever time series shapes, but this is not the case, eg:
```python
In [13]: from tslearn.metrics import itakura_mask                                                                                                                                                                                   
In [14]: itakura_mask(10, 3)                                                                                                                                                                                                        
Out[14]: 
array([[ 0., inf, inf],
[inf, inf, inf],
[inf, inf, …
```

[MRG] Sakoe-Chiba band and Itakura parallelogram broken in DTW computations

---

.travis.yml
tslearn/docs/conf.py
tslearn/docs/gen_modules/tslearn.utils.rst
tslearn/docs/index.rst
tslearn/tests/test_utils.py
tslearn/utils.py

The idea is to have a way to easily cast time series datasets from/to tslearn format to/from formats used by other python time series libraries.
I started with `pyts`. @johannfaouzi could you tell if what I assume to be the type of `pyts` datasets is OK or not?
The full list I would like to have would be:

Add utilities to cast from/to other python time series packages

---

tslearn/__init__.py
tslearn/tests/test_estimators.py
tslearn/tests/test_shapelets.py

Because the test folder didn't have an `__init__.py` file it was not considered to be a python module and was not included in wheels.
This adds it, which would make running tests on wheels easier in #150 with,
```
pytest --pyargs tslearn
```
this will run tests on the installed version of tslearn (installed from wheels or by other means).

MAINT Include test folder in wheels

---

tslearn/barycenters.py
tslearn/docs/examples/plot_barycenters.py
tslearn/docs/gen_modules/tslearn.barycenters.rst
tslearn/metrics.py
tslearn/neighbors.py
tslearn/tests/test_barycenters.py

As suggested (loooong ago) in #45 , there exist a vectorized form of the DBA algorithm. I have implemented it, and I like it because:
* it it strictly equivalent to DBA
* the code is more readable imho
* it is a bit faster:
```python
import numpy as np
import time
from tslearn.barycenters import dtw_barycenter_averaging_mm, dtw_barycenter_averaging
__author__ = 'Romain Tavenard romain.tavenard[at]univ-rennes2.fr'
n, sz, d = 500, 200, 10
data = np.random.randn(n, sz, d)
t0 = time.time()
bar = dtw_barycenter_averaging_mm(X=data)
print("Elapsed time for MM version: %f" % (time.time() - t0))
t0 = time.time()
bar = dtw_barycenter_averaging(X=data)
print("Elapsed time for DBA version: %f" % (time.time() - t0))
```
gives:
```
Elapsed time for MM version: 25.453088
Elapsed time for DBA version: …
```

[WIP] Implement MM algorithm for DBA

---

setup.py
tslearn/__init__.py
tslearn/tests/test_estimators.py

Followup on https://github.com/rtavenar/tslearn/pull/154
Related to https://github.com/rtavenar/tslearn/issues/150
Sorry, it looks like previous PR was not enough. Some changes to `setup.py` were also necessary.

MAINT More fixes to include test/ folder in sdist

---

CHANGELOG.md
tslearn/preprocessing.py

This is a redo of #175; rebasing to the dev branch got hairy so I'm just making a new PR along with the suggested additions from https://github.com/rtavenar/tslearn/pull/175#issuecomment-571482396
-----------
If a time series with any `NaN` values is passed to `TimeSeriesScalerMeanVariance.fit_transform()` or `TimeSeriesScalerMinMax.fit_transform()` the transformed time series returns as all `NaN`
E.g:
```
In [1]: from tslearn.preprocessing import TimeSeriesScalerMeanVariance                                                                
In [2]: from numpy import nan                                                                                                         
In [3]: TimeSeriesScalerMeanVariance().fit_transform([0, nan, 6]) …
```

[MRG] Disregard NaNs in preprocessing

---

.gitignore
tslearn/docs/contributing.rst
tslearn/docs/index.rst

Fixes #195 
This PR updates the [CONTRIBUTING.md](https://github.com/rtavenar/tslearn/blob/master/CONTRIBUTING.md) file and put the changes in a new file in the documentation:
* The file is converted from MD to RST;
* The file is added in the TOC;
* The commands to locally check the changes are updated;
* `.gitignore` is updated with some documentation stuff.
@rtavenar @GillesVandewiele 
@rtavenar: you can allow building the documentation for PR by [sending an email to the support of RTD](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html); it's very convenient (specially for people who don't do it locally).
@rtavenar: The `dev` branch is outdated for some stuff (like the `CONTRIBUTING.md` file for instance). It would be nice to update it since it's the …

[MRG] Add Contributing page in the documentation

---

README.md

In the past there have been some issues raised on not being able to easilly install `tslearn` via `pip` (see e.g. #84 and #132). Even though these issues are closed there is an easy fix for this given by [PEP-518](https://www.python.org/dev/peps/pep-0518/). This PR adds a `pyproject.toml` file which makes it possible to install `tslearn` from source by simply using `pip`.
I'm curious to hear any feedback on the idea of including this.

Add pyproject.toml

---

CHANGELOG.md
tslearn/svm.py
tslearn/tests/test_svm.py

Hi there,
When improving the doc examples, I found out that gamma was not set properly by `TimeSeriesSVC` and `TimeSeriesSVR` when the "gak" kernel was used.
@GillesVandewiele @johannfaouzi can any of you check that this was indeed a bug?
If it was, I would suggest we merge that PR to master and integrate the bugfix in the next patch release.

Fixed a bug that ignored the user-specified gamma value with TimeSeriesSVC and TimeSeriesSVR and gak kernel

---

tslearn/barycenters.py
tslearn/docs/dtw.rst
tslearn/docs/examples/plot_barycenters.py
tslearn/docs/variablelength.rst

These are the changes:
- better overview in the `tslearn.barycenter` module
- that module now links to the `plot_barycenter.py` example
- textual overview over the four methods added
- some inline comments + code is shorter
- all methods use the same number of iterations and tolerance for early stopping
- the plot is visually a little bit nicer
- get rid of the convergence warning of `dtw_barycenter_averaging_subgradient()` [still TODO]

Improve the documentation and examples on barycenters

---

.gitignore
tslearn/docs/contributing.rst
tslearn/docs/index.rst

This PR is identical to #197 expect that the target branch is `master` instead of `dev`.
By the way did you have news from RTD? It does not seem to build the documentation for PR. If they have activated the feature for this project, you have to configure the webhook (see [at the bottom of this page](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html)).

[MRG] DOC: Add contributing guide

---

tslearn/clustering.py
tslearn/preprocessing.py
tslearn/tests/test_clustering.py

This PR is a follow-up to Issue #215 .
The point is that it makes little sense to compute initial centroids using kmeans++ based on euclidean distances if the clustering is intended to be run wrt DTW or softDTW. So this PR adds a custom `_k_init` (adaptation from the one in scikit-learn) to the clustering module that draws samples wrt the target metric.

[WIP] Better kmeans initialization

---

README.md

Hi Romain,
Just a quick PR that replaces rtavenar by tslearn-team in the URLs of the README. I've tested all the links I changed and they should work.

Replace "rtavenar" with "tslearn-team" in README

---

CHANGELOG.md
tslearn/clustering.py
tslearn/neighbors.py
tslearn/preprocessing.py
tslearn/shapelets.py
tslearn/svm.py
tslearn/tests/sklearn_patches.py
tslearn/utils.py

This PR ensures that if an estimator can deal with variable-length inputs, then the only constraint at test time is that the number of features is equal to that provided at fit time.
This is a bugfix for #220

[MRG] Better shape checks at test time

---

tslearn/svm.py
tslearn/tests/test_svm.py

Starting from v0.4, the method `support_vectors_time_series_` is deprecated.
The way I coded it lead to a bug when calling it. This PR is a bugfix for this unwanted behavior.

[MRG] Bugfix: deprecated method in svm classes was unavailable

---

docs/conf.py

Now that the doc is front and center on Google it became slightly hard for geeks to reach the Code of tslearn.
I added a button at the top of the documentation that links toward the github page for tslearn.

[WIP] Add link to GitHub Code in the documentation

---

CONTRIBUTING.md

After PyCQA/pycodestyle#466, `pep8` was reneamed to `pycodestyle` a long time ago (but still checks for PEP8). This edit reflects that (it gave me a warning about it upon installation).

Small update to CONTRIBUTING.md

---

tslearn/datasets.py
tslearn/utils.py

This PR improves the documentation (inline and user facing) around `UCR_UEA_datasets.load_dataset()` and prints more specific error messages. Also properly closes all file descriptors after use & actually respect the `use_cached=False` case in `UCR_UEA_datasets.load_dataset()`.
It also uses the `warnings` module for ... warnings. The rationale for that was: (1) more helpful error messages due to the included stack trace excerpt and (2) the possibility to selectively disable such warnings in user or library code. AFAIK, that's what libraries like numpy do as well, instead of raw `sys.stderr.write()`. As I've just seen, this also seems to be the only place where that was used instead of the `warnings` module so maybe it was more of a residue.
Developed as part of debugging #282 and replaces …

Improve warnings and documentation in UCR_UEA_datasets 

---

.gitignore
tslearn/cycc.pyx
tslearn/hdftools.py
tslearn/utils.py

Modernizes the `tslearn.utils` module by removing code that was kept for Python versions that do not exist any more and using generator expressions and mainly simpler code in many places.
I also benchmarked the replacement for `time_series_to_str()`:
```python
>>> timeit(setup='import numpy as np;from io import StringIO;x = np.linspace(0,10,100); x=np.array((x,x,x))',stmt='i=StringIO();np.savetxt(i, x.T, fmt="%.18e", newline="|",encoding="bytes");s=i.getvalue()[:-1]', number=10000)
4.755633597000269
>>> timeit(setup='import numpy as np;from tslearn.utils import time_series_to_str;x = np.linspace(0,10,100); x=np.array((x,x,x))',stmt='time_series_to_str(x)', number=10000)
4.712957062001806
```
And for `str_to_time_series()`:
```python
timeit(setup='import numpy as np;from io import …
```

Modernize utils package

---

tslearn/tests/test_utils.py
tslearn/utils.py

The helper method `_arraylike_copy(thing)` can be easily replaced by `numpy.array(thing, copy=True)`. It was only used in `to_time_series()`. The docstring now explicitly says that `to_time_series()` always returns a *copy*.

Remove unnecessary helper method _arraylike_copy() from utils

---

azure-pipelines.yml

Also test on python version 3.9 and updates some VM images to their newest version. This way, we will find bugs in our repository CI arising from incompatibility with newer versions, before users will complain.
**EDIT:** This only updates the tools and not the python version to 3.9, which will be tracked in a separate issue (#322) as it is not ready to use for now.

Update CI images and tools

---

docs/requirements_rtd.txt
pyproject.toml
tslearn/__init__.py
tslearn/metrics/dtw_variants.py
tslearn/tests/test_metrics.py

This pull request fixes #354 and raises a ValueError when one input of dtw_path is an empty sequence or is a only nans sequence. The root of the bug is the numba.njit decorated function `_return_path`, however the numba documentation states that `raise` construct is partially supported inside njit decorated function.
I also added a test to ensure that this issue would never occur.

Fixed bug in dtw_path when one input is all nans or with empty length

---

setup.py

This makes it easier for automatic license checkers to verify the license of this package.

Add license information to package metadata

---

.github/workflows/build_wheels.yml
azure-pipelines.yml
pyproject.toml

Fixes: #372 #316
Drops python 3.5 support

[MRG] Deprecate python3.5 and build wheels for python3.9 and 3.10

---

tslearn/metrics/dtw_variants.py

I fixed issue #271 .
I implemented dimensions of timeseries check that raises ValueError('dimension mismatch') when the feature dimensions of the two input timeseries(s1,s2) are different.
Also, if I'm not mistaken, I think this process is also needed in the dtw_path function, so I added it there as well.
I would be happy to receive your feedback if this pull request is not appropriate.
Thanks.
(Sorry, the name of the branch was inappropriate, so I resubmit the PR again.)

[MRG] Check time series shape and output meaningful error for DTW

---

azure-pipelines.yml

macOS-10.15 will soon not be supported anymore : https://github.com/actions/runner-images/issues/5583
The continuous integration tests with macOS-10.15 are already not supported anymore in some recent other pull requests in tslearn.

[MRG] Newer macOS version in azure-pipelines.yml

---

tslearn/metrics/__init__.py

Without it `from tslearn.metrics import *` throws a `AttributeError: module 'tslearn.metrics' has no attribute 'lcss_path_from_metricctw_path'`. Haven't found a related issue.

[MRG] Fix missing comma in metrics.__init__

---

tslearn/clustering/kshape.py
tslearn/metrics/cycc.py

The KShape test is failing on MacOS.

Fix KShape failing continuous integration test on MacOS

---

azure-pipelines.yml
tslearn/shapelets/shapelets.py
tslearn/tests/sklearn_patches.py

This PR is related to the following issue: https://github.com/tslearn-team/tslearn/issues/426 which is related to a test error in the continuous integration tests of the main branch.
This bug was first noticed in continuous integration tests of the PR https://github.com/tslearn-team/tslearn/pull/411 (which is now merged), but this bug seems unrelated to the PR.
The continuous integration tests are failing with Linux but they pass with Windows and MacOS.
I use Linux and Python 3.8, and the tests pass on my local computer.
The failing test is related to the test the class tslearn.shapelets.shapelets.LearningShapelets by functions:
test_all_estimators (tslearn/tests/test_estimators.py) --> check_estimator (tslearn/tests/test_estimators.py) --> check_pipeline_consistency …

Fix LearningShapelets continuous integration test error on Linux

---

azure-pipelines.yml

This PR aims at solving on `ImportError` on Windows and MacOS (not on Linux).
In the file: `tslearn/tests/sklearn_patches.py`
There is the import: 
```
try:
from sklearn.utils.estimator_checks import (
_pairwise_estimator_convert_X as pairwise_estimator_convert_X,
_choose_check_classifiers_labels as choose_check_classifiers_labels
)
except ImportError:
from sklearn.utils.estimator_checks import (
pairwise_estimator_convert_X,
choose_check_classifiers_labels
)
```
which raises the following ImportError:
```
==================================== ERRORS ====================================
______________ ERROR collecting tslearn/tests/sklearn_patches.py _______________
tslearn/tests/sklearn_patches.py:56: in <module>
from sklearn.utils.estimator_checks import (
E   ImportError: cannot import …
```

Fix Import Error sklearn pairwise_estimator_convert_X

---

CHANGELOG.md

The current tslearn version (0.5.2) has been released on August 16, 2021: https://pypi.org/project/tslearn/#history
On tslearn main branch, a change of constraint about the Numpy version has solved the following issue: 
https://github.com/tslearn-team/tslearn/issues/399#issuecomment-1373121143
The current PR aims at updating the file `CHANGELOG.md` before release of tslearn version 0.5.3.
This new version will solve the issue mentioned previously.

Update CHANGELOG.md before release of tslearn version 0.5.3

---

README.md

Dear all,
This PR is to fix a hyperlink rot of the documentation "hyper-parameter tuning and pipelines" in README.md.
Regards,
Yichang

[MRG] Fix link to <hyper-parameter tuning and pipelines> in README.md

---

tslearn/shapelets/shapelets.py

This commit updates the data type from np.int to np.int_ in locate method of LearningShapelets. The change ensures compatibility with the NumPy library given that using the aliases of builtin types like np.int is deprecated.

Update locate returned data type from np.int to np.int_

---

tslearn/datasets/ucr_uea.py

The UEA & UCR Time Series Classification Repository has changed the url used to download its dataset zip files.
The previous url was:
https://www.timeseriesclassification.com/Downloads
It is now:
https://www.timeseriesclassification.com/ClassificationDownloads
For example, for the dataset "ECG200", the url was:
https://www.timeseriesclassification.com/Downloads/ECG200.zip
and is now:
https://www.timeseriesclassification.com/ClassificationDownloads/ECG200.zip

Update url of UCR UEA dataset zip files

---

CHANGELOG.md
azure-pipelines.yml

Python version 3.7 end of life's date is 2023-06-27:
https://devguide.python.org/versions/#supported-versions

Remove support for Python 3.7

---

tslearn/clustering/kmeans.py

The version 1.3.0 of `scikit-learn` has been released on June 30, 2023:
https://pypi.org/project/scikit-learn/#history
Here is the `Changelog` of version 1.3.0:
https://scikit-learn.org/dev/whats_new/v1.3.html
Amoung these differences, there is:
Enhancement The sample_weight parameter now will be used in centroids initialization for [](url) [cluster.KMeans](https://scikit-learn.org/dev/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans), [cluster.BisectingKMeans](https://scikit-learn.org/dev/modules/generated/sklearn.cluster.BisectingKMeans.html#sklearn.cluster.BisectingKMeans) and [cluster.MiniBatchKMeans](https://scikit-learn.org/dev/modules/generated/sklearn.cluster.MiniBatchKMeans.html#sklearn.cluster.MiniBatchKMeans). This change will break backward compatibility, …

Fix readthedocs failing test due to release of scikit-learn 1.3.0

---

CHANGELOG.md
azure-pipelines.yml
requirements.txt
requirements_nocast.txt
tslearn/backend/__init__.py
tslearn/backend/pytorch_backend.py
tslearn/tests/test_estimators.py
tslearn/tests/test_metrics.py

Init file in `tslearn/backend` imports torch backend, which imports torch. This causes an import error when torch is not installed. This change fixes this issue by removing extra import in `tslearn/backend/__init__.py`
Additionally, this change fixes failing tests when torch is not installed.
Fixes #462
I tried to run the tests locally, but some of them fail with and without pytorch being installed, so I can't say for sure if I fixed all test cases.
When this is fixed, I think some users will appreciate a new release, since the latest version is breaking for everybody who didn't install pytorch. To make things slightly worse, the latest version of pytorch is incompatible with the latest version of tensorflow: https://github.com/pytorch/pytorch/issues/97580, therefore the temporary fix of …

[MRG] Fix import error when torch is not installed.

---

tslearn/barycenters/softdtw.py
tslearn/bases/bases.py
tslearn/matrix_profile/matrix_profile.py
tslearn/shapelets/shapelets.py
tslearn/svm/svm.py
tslearn/tests/sklearn_patches.py
tslearn/tests/test_matrixprofile.py
tslearn/tests/test_serialize_models.py
tslearn/utils/cast.py

This PR has the same objective than the PR #468: to fix errors related to deprecated `np.bool`, `np.int` and `np.float` and arrays of inhomogeneous shape.
The package `black` has been used in the PR #468 on the modified files to reformat the codes, which makes the PR difficult to review.
This PR aims to be cleaner, avoiding the use of the package black on the modified files.

Fix errors deprecated np.bool, np.int and np.float and array of inhomogeneous shape

---

azure-pipelines.yml
tslearn/tests/sklearn_patches.py

All the tests related to Python 3.10 are failing:
- codecov Python 3.10
- linux_without_torch Python 3.10
- macOS Python 3.10
- windows Python 3.10
The error message is the following:
```
+ python -m pip install scikit-learn==1.0
Collecting scikit-learn==1.0
Downloading scikit-learn-1.0.tar.gz (7.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 13.4 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): still running...
Preparing metadata (pyproject.toml): finished with status 'error'
error: subprocess-exited-with-error
× Preparing …
```

Fix failing tests for Python 3.10

---

tslearn/metrics/soft_dtw_loss_pytorch.py
tslearn/tests/test_metrics.py

This PR is related to the issue https://github.com/tslearn-team/tslearn/issues/473 reporting an error message when `SoftDTWLossPytorch`  with option `normalize=True` is used on inputs of different lengths.
The bug is coming from the use of `torch.cat` (https://pytorch.org/docs/stable/generated/torch.cat.html) which impose the lengths of the inputs to be equal. (The shape of the inputs is `[batch_size, length, dim]`.)
The use of `torch.cat` is removed in this PR.

 Fix bug related to SoftDTWLossPytorch with option normalize=True when used on inputs of different lengths

---

tslearn/bases/bases.py

A test is failing for Python 3.9 and Python 3.10:
`FAILED tslearn/tests/test_serialize_models.py::test_serialize_kshape`
The error is the following:
```
____________________________ test_serialize_kshape _____________________________
def test_serialize_kshape():
n, sz, d = 15, 10, 3
rng = numpy.random.RandomState(0)
time_series = rng.randn(n, sz, d)
X = TimeSeriesScalerMeanVariance().fit_transform(time_series)
ks = KShape(n_clusters=3, verbose=True)
_check_not_fitted(ks)
ks.fit(X)
_check_params_predict(ks, X, ['predict'])
seed_ixs = [numpy.random.randint(0, X.shape[0] - 1) for i in range(3)]
seeds = numpy.array([X[i] for i in seed_ixs])
ks_seeded = KShape(n_clusters=3, verbose=True, init=seeds)
_check_not_fitted(ks_seeded)
ks_seeded.fit(X)
>       _check_params_predict(ks_seeded, X, …
```

Fix error in function from_hdf5

---

tslearn/backend/__init__.py
tslearn/backend/backend.py
tslearn/backend/numpy_backend.py
tslearn/backend/pytorch_backend.py
tslearn/metrics/ctw.py
tslearn/metrics/dtw_variants.py
tslearn/metrics/soft_dtw_fast.py
tslearn/metrics/softdtw_variants.py
tslearn/metrics/utils.py
tslearn/tests/test_metrics.py

In the functions of the folder `tslearn/metrics` supporting the backend optional input parameter `be`, cast the input data to the backend option when possible (using `be.array`).
Test the functions of the file `test_metrics.py` for different input data types (list, numpy, pytorch) and different backend options (numpy, pytorch, None). Two nested `for` loops are used.
Therefore the following generic metric function is tested for different input data types and backend options:
```
def metric_function(s1, s2, be=None):
be = instantiate_backend(be, s1, s2)
s1 = be.array(s1)
s2 = be.array(s2)
...
```

Cast the input data to backend option and test functions in metrics for different input data types and different backend options.

---

tslearn/metrics/soft_dtw_fast.py
tslearn/metrics/softdtw_variants.py
tslearn/tests/test_metrics.py

In the file [tslearn/metrics/soft_dtw_fast.py](https://github.com/tslearn-team/tslearn/pull/481/files#diff-42cda75332819109d4b1229c1304c8c849e5545a45818b2ee558e11e20b7ff0d), the functions `_soft_dtw`, `_soft_dtw_batch`, `_soft_dtw_grad` and `_soft_dtw_grad_batch` do not return of value, they modify directly the input value as a mutable object.
An error was introduced in the PR #479 casting the input values to the selected backend with:
```
D = be.array(D, dtype=be.float64)
R = be.array(R, dtype=be.float64)
gamma = be.array(gamma, dtype=be.float64)
```
Indeed, `be.array` cast the input values to the desired backend, but it creates a copy input values. 
Therefore the input values will not be modified as mutable objects.
These lines are removed in this PR.
We add a test to make sure that …

Fix error in _soft_dtw, add test and add option compute_with_backend in soft_dtw and soft_dtw_alignment.

---

.readthedocs.yml

The `readthedocs` test is failing on the main branch with the following error message:
`The configuration key "build.image" is deprecated. Use "build.os" instead to continue building your project. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os`
Indeed, `build.image` is deprecated since Monday, October 16, 2023 and is now replaced by `build.os`:
https://blog.readthedocs.com/use-build-os-config/
Specific details to write the `.readthedocs.yml` file can be found at:
https://docs.readthedocs.io/en/stable/config-file/v2.html

Fix readthedocs fail test changing build.image into build.os

---

tslearn/metrics/dtw_variants.py

Specify the possible shapes of the input arrays of the metric functions of the file `dtw_variants.py` in the docstrings.
For example:
```
s1 : array-like, shape=(sz1, d) or (sz1,)
A time series. If shape is (sz1,), the time series is assumed to be univariate.
```
or
```
dataset1 : array-like, shape=(n_ts, sz, d) or (sz, d) or (sz,)
A dataset of time series. If shape is (sz, d), the dataset is composed of a unique time series. 
If shape is (sz,), the dataset is a composed of a unique univariate time series.
```

Precise the shape of the input arrays of functions in dtw_variants.py

---

tslearn/metrics/ctw.py
tslearn/metrics/dtw_variants.py
tslearn/metrics/utils.py
tslearn/utils/utils.py

Specify the possible shapes of the input arrays of the metric functions of the file `ctw.py` in the docstrings.
For example:
```
s1 : array-like, shape=(sz1, d) or (sz1,)
A time series. If shape is (sz1,), the time series is assumed to be univariate.
```
or
```
dataset1 : array-like, shape=(n_ts, sz, d) or (n_ts, sz) or (sz,)
A dataset of time series. If shape is (n_ts, sz), the dataset is composed of univariate time series. 
If shape is (sz,), the dataset is a composed of a unique univariate time series.
```

Specify in the docstrings the shapes of the input arrays of the functions of the file ctw.py

---

tslearn/metrics/cycc.py
tslearn/metrics/cysax.py
tslearn/metrics/sax.py
tslearn/metrics/soft_dtw_fast.py
tslearn/metrics/softdtw_variants.py

Improve the docstrings in several metric functions, in particular the functions of the files `cycc.py`, `cysax.py`, `sax.py` and `soft_dtw_fast.py`.

Improve docstrings in several metric functions

---

tslearn/metrics/softdtw_variants.py

Simplify the functions `_gak` and `_njit_gak` in `softdtw_variants.py`
It seems that the input variables `s1` and `s2` are not necessary in the functions `_gak` and `_njit_gak`.
Indeed, these variables `s1` and `s2` are only used to determine the length `l1` and `l2` of these time series.
This information can also be obtained from the shape of the input array `gram` which is equal to `(l1, l2)`.

Simplify _gak and _njit_gak in softdtw_variants.py

---

azure-pipelines.yml
docs/backend.rst
docs/quickstart.rst
tslearn/metrics/dtw_variants.py
tslearn/metrics/softdtw_variants.py

This PR improves the documentation about the backends to explain how they work.
We will add information about the backends (how it works, how to select the backend, what happens if it is not selected...)  in the Quick-start guide:
https://github.com/tslearn-team/tslearn/blob/main/docs/quickstart.rst
and add a file named `backend.rst` in the folder `main/docs`.
We will also add information about the backends and examples in the docstrings of the functions `dtw` (https://github.com/tslearn-team/tslearn/blob/main/tslearn/metrics/dtw_variants.py) and `soft_dtw` (https://github.com/tslearn-team/tslearn/blob/main/tslearn/metrics/softdtw_variants.py).

Improve backend docstrings

---

tslearn/shapelets/shapelets.py
tslearn/tests/test_shapelets.py

Fix error in `LearningShapelets` when the input parameter `n_shapelets_per_size` equals `None`.
The error related to this PR is detailed in the issue https://github.com/tslearn-team/tslearn/issues/495.

Fix error in LearningShapelets when the input parameter n_shapelets_per_size equals None

---

docs/backend.rst
tslearn/metrics/ctw.py
tslearn/metrics/dtw_variants.py
tslearn/metrics/soft_dtw_fast.py
tslearn/metrics/softdtw_variants.py
tslearn/metrics/utils.py
tslearn/utils/utils.py

Clarify the docstrings of optional input parameters `be` and `compute_with_backend`.

Clarify docstrings of backend parameters

---

tslearn/clustering/utils.py

Investigating on the issue https://github.com/tslearn-team/tslearn/issues/507, I found a recursion error in the function `silhouette_score` when the input parameter metric is callable.
The error can be reproduced running the following code:
```
import numpy as np
from tslearn.clustering.utils import silhouette_score
from tslearn.metrics import dtw
n_ts = 4
sz = 3
d = 2
X = np.random.randn(n_ts, sz, d)
labels = [0] * (n_ts // 2) + [1] * (n_ts // 2)
score = silhouette_score(
X=X,
labels=labels,
metric=dtw)
print(score)
```
The following error is returned:
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```
The error is related to the end of the function `silhouette_score`:
```
def sklearn_metric(x, y):
return metric(to_time_series(x.reshape((sz, d)), …
```

Fix error in function silhouette_score when metric is callable

---

docs/user_guide/lcss.rst
tslearn/metrics/dtw_variants.py

Fix a few mistakes in the LCSS documentation:
- Fix a typo in `epsilon` and `delta` mathematical symbols
- Fix an error in `epsilon` and `delta` data types
- In the pseudocode of the function `lcss`, normalize the returned result by dividing by `min(n, m)` 
- Precise that the values returned by LCSS range from 0 to 1, the value 1 being taken when the two time series completely match. It was written that for all `x`, `lcss(x, x) = 0` instead of `lcss(x, x) = 1`. This mistake has been noticed in Issue https://github.com/tslearn-team/tslearn/issues/509
- Remove a wrong sentence saying that the clustering algorithm `TimeSeriesKMeans` can be used with the `lcss` metric

Fix LCSS documentation

---

README.md

fix broken contributing link in the readme.  
I assume from the previous link that you wanted to have the link inside github - another option is to redirect to https://tslearn.readthedocs.io/en/stable/contributing.html.

[MRG] Docs: fix broken link in README.md

---

tslearn/preprocessing/__init__.py
tslearn/preprocessing/preprocessing.py
tslearn/tests/test_preprocessing.py
tslearn/utils/__init__.py
tslearn/utils/utils.py

Fixes #564 Add an TimeSeriesImputer class to handle basic imputation. Imputation is done per time series, using one of the available method (mean, median, forwardfill , backward fill). When used with variable lenght time series, the keep_trailing_nans parameter controls whether the nans padding is to be processed by the imputer.

Add imputation capability
