tslearn-team/tslearn

README.md

Great package! 
Just found  the documentation I was unaware of before. Included a link in the readme to help other users.

updated readme with a link to readthedocs

---

tslearn/piecewise.py

See Issue 89: https://github.com/rtavenar/tslearn/issues/89

Fixing Issue #89: 1D-SAX default 'sigma_l'

---

README.md
tslearn/docs/index.rst

C++ build tools should be available on the machine in order to install through the pip

Add pre-requisites section

---

CHANGELOG.md
tslearn/shapelets.py
tslearn/tests/test_shapelets.py

This PR adds a `set_weights` method to the `ShapeletModel` class.
This should not be merged before v0.3 since it changes the public API.

[WIP] Add a way to set shapelets for a model manually

---

tslearn/docs/examples/plot_sdtw.py
tslearn/docs/gen_modules/tslearn.metrics.rst
tslearn/metrics.py
tslearn/tests/test_metrics.py

[MRG] Configurable subsequent DTW path computation

---

azure-pipelines.yml
conftest.py
tslearn/tests/test_utils.py
tslearn/utils.py

Working on setting up CI with Azure Pipelines

Azure pipelines setup

---

tslearn/docs/examples/plot_shapelet_locations.py

Sorry, did not see this small mistake in the title of the plot (wrong formatting).

Small bugfix in format string of plot_shapelet_location

---

.github/FUNDING.yml
azure-pipelines.yml
tslearn/docs/examples/plot_barycenter_interpolate.py
tslearn/docs/examples/plot_dtw.py
tslearn/docs/examples/plot_kernel_kmeans.py
tslearn/docs/examples/plot_kmeans.py
tslearn/docs/examples/plot_knn_search.py
tslearn/docs/examples/plot_knnts_sklearn.py
tslearn/docs/examples/plot_lb_keogh.py
tslearn/docs/examples/plot_neighbors.py
tslearn/docs/examples/plot_sax.py
tslearn/docs/examples/plot_sdtw.py
tslearn/docs/examples/plot_svm.py
tslearn/neighbors.py

This PR updates two examples: `LB_Keogh` and `DTW`.
Side note: there are two example with the same title for Learning Shapelets.
It could be nice to update the docstrings of most examples so that they are more detailed, if some people have some time to work on this.

Update a couple of examples

---

README.md

Issue 
https://github.com/tslearn-team/tslearn/issues/228

fix documentation URL from latest to stable

---

.travis.yml
azure-pipelines.yml
tslearn/bases.py
tslearn/clustering.py
tslearn/neighbors.py
tslearn/piecewise.py
tslearn/preprocessing.py
tslearn/shapelets.py
tslearn/svm.py
tslearn/tests/sklearn_patches.py
tslearn/tests/test_estimators.py
tslearn/utils.py

Better tag inheritance to match with latest scikit-learn versions

---

tslearn/docs/examples/classification/plot_svm.py
tslearn/svm.py

Fixes #236
EDIT: I still have to work on the docstrings 
Edit: done

[MRG] Better SVM classes

---

tslearn/clustering.py
tslearn/preprocessing.py
tslearn/shapelets.py
tslearn/tests/test_serialize_models.py
tslearn/tests/test_shapelets.py

[MRG] Remove deprecated arguments in preparation of v0.4

---

tslearn/bases.py
tslearn/clustering.py
tslearn/piecewise.py
tslearn/shapelets.py
tslearn/tests/test_serialize_models.py

Fixes #230 
@kushalkolar could you tell me if this corresponds to what you had in mind?

[MRG] Non-callable attributes that end in `_` are automatically registered for serialization

---

tslearn/neighbors.py
tslearn/piecewise.py
tslearn/tests/sklearn_patches.py
tslearn/tests/test_piecewise.py

[MRG] Scale parameter for SAX and 1dSAX classes

---

.gitignore
CHANGELOG.md
tslearn/docs/examples/misc/plot_matrix_profile.py
tslearn/docs/gen_modules/tslearn.matrix_profile.rst
tslearn/matrix_profile.py

Fixes #27 
The goal might not be to have the fastest implementation of matrix profiles in town, but a decent one that could transform a time series dataset into a `sklearn`-formatted one (no more time dimension in matrix profiles) easily.

[MRG] Implement Matrix Profile

---

tslearn/neighbors.py
tslearn/piecewise.py
tslearn/preprocessing.py
tslearn/tests/test_piecewise.py

@GillesVandewiele this is related to the point you made in #126

[MRG] SAX scaling operates at the dataset level

---

CHANGELOG.md
tslearn/clustering.py

[MRG] Implement transform method for kmeans

---

tslearn/docs/_static/custom.js
tslearn/docs/conf.py

In fact, the banner is added to any version that is not the 'stable' RTD version.
Fixes #228

[MRG] Add a warning banner to the 'latest' version of the docs

---

docs/examples/metrics/plot_ctw.py
docs/examples/metrics/plot_dtw.py
tslearn/bases.py
tslearn/metrics/__init__.py
tslearn/metrics/ctw.py
tslearn/metrics/dtw_variants.py
tslearn/neighbors.py
tslearn/tests/test_metrics.py
tslearn/tests/test_neighbors.py

This is an attempt to implement Canonical Time Warping in tslearn (relying on tslearn's DTW and sklearn's CCA).
Yet to do: ~~proper docs, example, tests, integration in kNN classes~~ (+ change the target to `master` once the PR on code refactoring is merged #273 )

Canonical Time Warping

---

tslearn/bases.py
tslearn/tests/test_serialize_models.py

[MRG] fix hyper-params being numpy arrays when using json serialization

---

.github/workflows/build_wheels.yml
.readthedocs.yml
azure-pipelines.yml

This PR:
- Uses the most recent Python versions in the automated scripts (Python 3.9)
- Uses the most recent GitHub action versions where applicable
- Closes #322

Also test on Python 3.9

---

CHANGELOG.md
tslearn/datasets/ucr_uea.py
tslearn/metrics/softdtw_variants.py

[WIP] Fix cdist_soft_dtw_normalized when two different datasets are provided

---

tslearn/backend/backend.py

Simplify the way the attributes and methods are defined in the class `Backend`.

Simplify backend

---

tslearn/metrics/ctw.py
tslearn/metrics/dtw_variants.py
tslearn/metrics/sax.py
tslearn/metrics/soft_dtw_fast.py
tslearn/metrics/softdtw_variants.py
tslearn/metrics/utils.py
tslearn/utils/utils.py

Improve the docstrings of the metric functions of the file `softdtw_variants.py`
Precise the shapes of the input on output arrays.

Improve the docstrings of the metric functions of the file softdtw_variants.py

---

azure-pipelines.yml
requirements.txt
requirements_tests.txt
tslearn/bases/bases.py
tslearn/clustering/kmeans.py
tslearn/clustering/kshape.py
tslearn/clustering/utils.py
tslearn/early_classification/early_classification.py
tslearn/metrics/ctw.py
tslearn/metrics/dtw_variants.py
tslearn/metrics/softdtw_variants.py
tslearn/neighbors/neighbors.py
tslearn/neural_network/neural_network.py
tslearn/piecewise/piecewise.py
tslearn/preprocessing/preprocessing.py
tslearn/svm/svm.py
tslearn/tests/sklearn_patches.py
tslearn/tests/test_estimators.py

Make sure azure pipelines tests are ok:
- Support scikit-learn 1.6.1 and induced numpy version
-  Fix depencies versions for python 3.8 3.9 3.10 on ubuntu / windows / macos latest plateforms
- Remove fixed scikit-learn / tensor flow version from jobs to ensure proper testing

Fix automated tests

---

setup.py

Add setup.py python version requirement

Supporting python 3.9+

---

docs/examples/metrics/plot_lcss_custom_metric.py
docs/user_guide/lcss.rst

Add the epsilon hyperparameter to docs to emphasize its importance.

Add eps parameter to docs
